### PR TITLE
fix: properly detect break statements within switch cases

### LINKED ISSUE #607: Switch case with while loop does not have break statement properly inserted
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
switch a
  when 'b'
    while false
      break
  when 'c'
    console.log 'Got here'
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=switch%20a%0A%20%20when%20'b'%0A%20%20%20%20while%20false%0A%20%20%20%20%20%20break%0A%20%20when%20'c'%0A%20%20%20%20console.log%20'Got%20here')

I get this output:

```js
switch (a) {
  case 'b':
    while (false) {
      break;
    }
  case 'c':
    console.log('Got here');
    break;
}
```

Here's what I expect it to be instead:

```js
switch (a) {
  case 'b':
    while (false) {
      break;
    }
    break;
  case 'c':
    console.log('Got here');
    break;
}
```

### PR DESCRIPTION
**Pull request by alangpierce**
Fixes #607.

Previously, we would detect if the switch case body ends with a `break` token,
but that's actually not good enough; we should directly check that the last
statement is a break statement.

### CODE REVIEW

File: src/stages/main/patchers/SwitchCasePatcher.js [hunk 1]
```diff
@@ -139,13 +139,14 @@ export default class SwitchCasePatcher extends NodePatcher {
...
-    } else {
-      return null;
+  hasExistingBreak(): boolean {
+    if (!(this.consequent instanceof BlockPatcher)) {
+      return false;
     }
+    let lastStatement = this.consequent.statements[this.consequent.statements.length - 1];
+    return lastStatement &&
+        lastStatement.node.type === 'Identifier' &&
+        lastStatement.node.data === 'break';
```
Comment (eventualbuddha) [inline src/stages/main/patchers/SwitchCasePatcher.js]: Related, it seems wrong that this is an identifier and not a `BreakStatement` or something.
