### PR TITLE
fix: improve the process of patching code for use elsewhere

### LINKED ISSUE #498: Crash when using `not of` in an IIFE-style loop
decaffeinate is crashing on my CoffeeScript input:

```coffee
a = (b for b of c when d not of e)
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=a%20%3D%20(b%20for%20b%20of%20c%20when%20d%20not%20of%20e))

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (4:15)
  2 |   result = [];
  3 |   for (b in c) {
> 4 |     if (d in e)) {;
    |                ^
  5 |       result.push(b);
  6 |     };
```

This is similar to #491, but has a different underlying cause.

### PR DESCRIPTION
**Pull request by alangpierce**
Fixes #498

Previously, you might call `patch` on a sub-patcher, then use `slice` to get the
generated code, but this didn't always work out well, since we always do
`insertLeft` (for magic-string sanity), so slice would sometimes miss an
open-paren inserted at the start.

This commit changes the loop filter case to use this new method, but probably
other code paths should be moved over to it as well in the future.

### CODE REVIEW

File: src/patchers/NodePatcher.js [hunk 1]
```diff
@@ -233,6 +233,28 @@ export default class NodePatcher {
   }
 
   /**
+   * Patch the given expression and get the underlying generated code. This is
+   * more robust then calling patch and slice directly, since it also includes
```
Comment (eventualbuddha) [inline src/patchers/NodePatcher.js]: Silly thing to point out, but this should be "than" instead of "then".

Comment (alangpierce) [inline src/patchers/NodePatcher.js]: Oops :-)
