### PR TITLE
fix: allow duplicate class declarations

### LINKED ISSUE #855: Declaring the same class name twice causes a crash
decaffeinate is crashing on my CoffeeScript input:

```coffee
class A
class A
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=class%20A%0Aclass%20A)

I get this error:

```
Cannot read property 'file' of undefined
```

In CoffeeScript, class statements just cause an assignment, while in JavaScript, they count as a declaration, so you can't have two with the same name.

### PR DESCRIPTION
**Pull request by alangpierce**
Fixes #855

We now track class declarations in our scope, and only use the normal class
syntax if the class being patched is also the declaration site (the first
assignment seen by the scope).

This also lets us remove a special case in the `initClass` patching in the
normalize step. We don't need to explicitly create an assignment anymore,
because one is created automatically due to a variable with the same name being
declared above the class declaration.

### CODE REVIEW

File: test/class_test.js [hunk 1]
```diff
@@ -1305,4 +1305,14 @@ describe('classes', () => {
...
     `);
   });
+
+  it('allows two class declarations with the same name', () => {
+    check(`
+      class A
+      class A
+    `, `
+      class A {}
+      A = class {};
```
Comment (eventualbuddha) [inline test/class_test.js]: Wouldn't we want to keep the name on the class expression? It could matter.
